# https://github.com/settings/developers
GITHUB_CLIENT_ID: XXXXXXXXXXXXXXXXXXXXXXXXX
GITHUB_CLIENT_SECRET: XXXXXXXXXXXXXXXXXXXXX
GITHUB_WEBHOOK_SECRET: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
GITHUB_APP_ID: xxxxxxxxxxxxxxxxxxxxx

# https://console.developers.google.com/apis/credentials
GOOGLE_CLIENT_ID: xxxxxxxxxxxxxxxxxxxxxxxxx
GOOGLE_CLIENT_SECRET: xxxxxxxxxxxxxxxxxxxxx

# https://dashboard.stripe.com/account/apikeys
STRIPE_SECRET_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
STRIPE_ENDPOINT_SECRET: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
